---
title: "multiple score summary"
author: "Yixiao Chen"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(tidyr)
library(dplyr)
library(stringr)
library(readr)
```

```{r}
# create a list of file names
data <- c("1833_DETECT_CallExport_20220524.CSV",
          "1833_DETECT_CallExport_20220613.CSV",
          "1833_DETECT_CallExport_20220623.CSV",
          "1833_DETECT_CallExport_20220713.CSV",
          "1833_DETECT_CallExport_20220726.CSV",
          "1833_DETECT_CallExport_20220808.CSV",
          "1833_DETECT_CallExport_20220825.CSV",
          "1833_DETECT_CallExport_20220912.CSV",
          "1833_DETECT_CallExport_20220922.CSV",
          "1833_DETECT_CallExport_20221011.CSV",
          "1833_DETECT_CallExport_20221024.CSV",
          "1833_DETECT_CallExport_20221109.CSV",
          "1833_DETECT_CallExport_20221123.CSV",
          "1833_DETECT_CallExport_20221209.CSV",
          "1833_DETECT_CallExport_20221223.CSV",
          "1833_DETECT_CallExport_20230110.CSV",
          "1833_DETECT_CallExport_20230125.CSV",
          "1833_DETECT_CallExport_20230210.CSV",
          "1833_DETECT_CallExport_20230222.CSV",
          "1833_DETECT_CallExport_20230310.CSV",
          "1833_DETECT_CallExport_20230324.CSV")

# create an empty data frame to store the results
results <- data.frame(data_file = character(),
                      unique_ids = character(),
                      resCodeResult = character(),
                      score = character(),
                      stringsAsFactors = FALSE)
```


```{r}
# loop through the files and process each one
for (file_name in data) {
  call_history <- read_csv(paste0("~/UTHealth Houston/Cannell, Michael B - Outbound call logs/", file_name))
  
# get the IDs that have multiple scores but don't have a completed code
  df <- call_history %>%
    group_by(PTCARERPTNUM) %>%
    mutate(non_miss_score = sum(!is.na(SCORE))) %>%
    filter(non_miss_score > 1) %>%
    filter(!str_detect(resCodeResult, "^CO$|^97$|^98$")) %>%
    summarise(unique_ids = ifelse(!any(str_detect(resCodeResult, "^CO$|^97$|^98$")), PTCARERPTNUM, NA),
              score = paste0(SCORE),
              resCodeResult = paste0(unique(resCodeResult), collapse = ", ")) %>%
    drop_na(unique_ids) %>%
    mutate(data_file = file_name)
  
# add the results to the data frame
  results <- bind_rows(results, df)
}
```


```{r}
# write the results to a CSV file
write_csv(results, "multiple score issue.csv")
```

